#ifndef GTX_H
#define GTX_H


extern void GtxTmd_RotTransPersN1() ; // 0x800180AC

extern void GtxTmd_RotTransPersN() ; // 0x8001810C

extern void GtxTmd_DisplayLON() ; // 0x800181C4

extern void GtxTmd_DisplayLOFF() ; // 0x8001872C

extern void GtxTmd_Display3LOFF() ; // 0x80018BA0

extern void GtxTmx_Display4LOFF() ; // 0x80018E00

extern void GtxTmd_ApplyMIMe() ; // 0x80019014

extern void GtxTmx_Display3LON() ; // 0x800190A8

extern void GtxTmx_DisplayLON() ; // 0x80019240

extern void GtxShp_DisplayListLOFF() ; // 0x800197AC

extern void __SN_ENTRY_POINT() ; // 0x800199E4


#endif
