#include "THISDUST.H"
#include "BOSS2.H"


// decompiled code
// original method signature: 
// void /*$ra*/ Monster_Shot_Position(long x /*$s1*/, long y /*$s2*/, long z /*$s3*/, long shoot /*$s5*/)
 // line 34, offset 0x800adbe0
	/* begin block 1 */
		// Start line: 35
		// Start offset: 0x800ADBE0
		// Variables:
	// 		struct BOSS2_7fake pos; // stack offset -64
	// 		struct BOSS2_7fake rot; // stack offset -56
	// 		struct BOSS2_8fake col; // stack offset -48
	// 		struct BOSS2_7fake tar; // stack offset -40
	// 		struct _MONSTER *monst; // $v0
	// 		struct _D3_OBJECT *o; // $s4
	/* end block 1 */
	// End offset: 0x800ADDC8
	// End Line: 61

	/* begin block 2 */
		// Start line: 68
	/* end block 2 */
	// End Line: 69

/* WARNING: Control flow encountered bad instruction data */

void Monster_Shot_Position(long x,long y,long z,long shoot)

{
                    /* WARNING: Bad instruction - Truncating control flow here */
  halt_baddata();
}



// decompiled code
// original method signature: 
// void /*$ra*/ Monster_Animate_Child(struct _D3_OBJECT *obj /*$a0*/, long childID /*$s1*/, long AnimNr /*$s2*/)
 // line 105, offset 0x800addec
	/* begin block 1 */
		// Start line: 106
		// Start offset: 0x800ADDEC
		// Variables:
	// 		struct _D3_OBJECT *child; // $s0
	// 		struct _D3_OBJECT *waitfor; // $v1
	/* end block 1 */
	// End offset: 0x800ADE60
	// End Line: 120

	/* begin block 2 */
		// Start line: 230
	/* end block 2 */
	// End Line: 231

/* WARNING: Control flow encountered bad instruction data */

void Monster_Animate_Child(_D3_OBJECT *obj,long childID,long AnimNr)

{
                    /* WARNING: Bad instruction - Truncating control flow here */
  halt_baddata();
}



// decompiled code
// original method signature: 
// void /*$ra*/ Proto_ExplosionScript(struct _D3_OBJECT *o /*$s2*/, long loop /*$s5*/, long run /*$s6*/)
 // line 123, offset 0x800ade78
	/* begin block 1 */
		// Start line: 124
		// Start offset: 0x800ADE78
		// Variables:
	// 		struct _D3_OBJECT *tmp; // $s1
	// 		struct _D3_OBJECT *chld; // $s0
	// 		struct BOSS2_7fake pos; // stack offset -40
	// 		long i; // $s3
	/* end block 1 */
	// End offset: 0x800AE358
	// End Line: 219

	/* begin block 2 */
		// Start line: 266
	/* end block 2 */
	// End Line: 267

/* WARNING: Control flow encountered bad instruction data */

void Proto_ExplosionScript(_D3_OBJECT *o,long loop,long run)

{
                    /* WARNING: Bad instruction - Truncating control flow here */
  halt_baddata();
}



// decompiled code
// original method signature: 
// void /*$ra*/ MonstScript_Proto_FuncAttack()
 // line 223, offset 0x800ae380
	/* begin block 1 */
		// Start line: 224
		// Start offset: 0x800AE380
		// Variables:
	// 		struct _MONSTER *monst; // $s1
	// 		struct _D3_OBJECT *o; // $s0
	// 		struct _D3_OBJECT *target; // $s2
	// 		long tmp; // $v0
	/* end block 1 */
	// End offset: 0x800AE490
	// End Line: 254

	/* begin block 2 */
		// Start line: 556
	/* end block 2 */
	// End Line: 557

/* WARNING: Control flow encountered bad instruction data */
/* WARNING: Unknown calling convention yet parameter storage is locked */

void MonstScript_Proto_FuncAttack(void)

{
                    /* WARNING: Bad instruction - Truncating control flow here */
  halt_baddata();
}



// decompiled code
// original method signature: 
// void /*$ra*/ RobotProto_Init()
 // line 257, offset 0x800ae4a8
	/* begin block 1 */
		// Start line: 258
		// Start offset: 0x800AE4A8
		// Variables:
	// 		struct _MONSTER *monst; // $s0
	// 		struct _D3_OBJECT *o; // $s1
	/* end block 1 */
	// End offset: 0x800AE610
	// End Line: 299

	/* begin block 2 */
		// Start line: 626
	/* end block 2 */
	// End Line: 627

/* WARNING: Control flow encountered bad instruction data */
/* WARNING: Unknown calling convention yet parameter storage is locked */

void RobotProto_Init(void)

{
                    /* WARNING: Bad instruction - Truncating control flow here */
  halt_baddata();
}



// decompiled code
// original method signature: 
// void /*$ra*/ RobotProto_Func_Reflex()
 // line 303, offset 0x800ae624
	/* begin block 1 */
		// Start line: 304
		// Start offset: 0x800AE624
		// Variables:
	// 		struct _MONSTER *monst; // $s1
	// 		struct _D3_OBJECT *o; // $s2
	// 		struct _D3_OBJECT *target; // $s3
	// 		struct _D3_OBJECT *tmpobj; // $s0
	// 		struct _D3_OBJECT *tmpobj2; // $s3
	// 		struct M_OBJECT *mo; // $a0
	// 		long i; // $a0
	// 		long tmp; // $s4
	/* end block 1 */
	// End offset: 0x800AE9FC
	// End Line: 399

	/* begin block 2 */
		// Start line: 736
	/* end block 2 */
	// End Line: 737

/* WARNING: Control flow encountered bad instruction data */
/* WARNING: Unknown calling convention yet parameter storage is locked */

void RobotProto_Func_Reflex(void)

{
                    /* WARNING: Bad instruction - Truncating control flow here */
  halt_baddata();
}



// decompiled code
// original method signature: 
// void /*$ra*/ RobotProto_Func_Decisions()
 // line 402, offset 0x800aea1c
	/* begin block 1 */
		// Start line: 403
		// Start offset: 0x800AEA1C
		// Variables:
	// 		struct _MONSTER *monst; // $s0
	/* end block 1 */
	// End offset: 0x800AEA68
	// End Line: 411

	/* begin block 2 */
		// Start line: 946
	/* end block 2 */
	// End Line: 947

/* WARNING: Control flow encountered bad instruction data */
/* WARNING: Unknown calling convention yet parameter storage is locked */

void RobotProto_Func_Decisions(void)

{
                    /* WARNING: Bad instruction - Truncating control flow here */
  halt_baddata();
}



// decompiled code
// original method signature: 
// void /*$ra*/ RobotProto_Task_Action()
 // line 414, offset 0x800aea78
	/* begin block 1 */
		// Start line: 415
		// Start offset: 0x800AEA78
		// Variables:
	// 		struct _MONSTER *monst; // $s3
	// 		struct _D3_OBJECT *o; // $s2
	// 		struct _D3_OBJECT *target; // $v0
	// 		struct _D3_OBJECT *tmpobj; // $v0
	// 		struct M_OBJECT *mo; // $s4
	// 		long i; // $s0
	// 		long x; // $s1
	// 		long y; // $s0
	// 		long z; // $v1
	/* end block 1 */
	// End offset: 0x800AF004
	// End Line: 538

	/* begin block 2 */
		// Start line: 976
	/* end block 2 */
	// End Line: 977

/* WARNING: Control flow encountered bad instruction data */
/* WARNING: Unknown calling convention yet parameter storage is locked */

void RobotProto_Task_Action(void)

{
                    /* WARNING: Bad instruction - Truncating control flow here */
  halt_baddata();
}



// decompiled code
// original method signature: 
// void /*$ra*/ Proto_Scripting()
 // line 559, offset 0x800af040
	/* begin block 1 */
		// Start line: 560
		// Start offset: 0x800AF040
		// Variables:
	// 		struct _MONSTER *monst; // $s1
	// 		struct _D3_OBJECT *o; // $s2
	// 		struct _D3_OBJECT *target; // $a1
	// 		struct _D3_OBJECT *left; // $v0
	// 		struct _D3_OBJECT *right; // $s0
	// 		long tmp; // $s3
	/* end block 1 */
	// End offset: 0x800AF39C
	// End Line: 703

	/* begin block 2 */
		// Start line: 1292
	/* end block 2 */
	// End Line: 1293

/* WARNING: Control flow encountered bad instruction data */
/* WARNING: Unknown calling convention yet parameter storage is locked */

void Proto_Scripting(void)

{
                    /* WARNING: Bad instruction - Truncating control flow here */
  halt_baddata();
}



// autogenerated function stub: 
// void _boss7_bss_objend() /* _boss7_bss_objend method signature is not contained in the debug symbol data. This is likely either a library function or the game was compiled without debug symbols. Please refer to the TDR documentation for additional guidance. */
void _boss7_bss_objend() 
{ // line 809, offset 0x800af204
	return null;
}


// autogenerated function stub: 
// void Bosses_Explosion() /* Bosses_Explosion method signature is not contained in the debug symbol data. This is likely either a library function or the game was compiled without debug symbols. Please refer to the TDR documentation for additional guidance. */
void Bosses_Explosion() 
{ // line 885, offset 0x800af3b8
	return null;
}




