#include "THISDUST.H"
#include "MENU.H"


// decompiled code
// original method signature: 
// int /*$ra*/ Menu_BootupInitGfx()
 // line 359, offset 0x800bc134
	/* begin block 1 */
		// Start line: 360
		// Start offset: 0x800BC134
		// Variables:
	// 		int i; // $s4
	/* end block 1 */
	// End offset: 0x800BC210
	// End Line: 371

	/* begin block 2 */
		// Start line: 718
	/* end block 2 */
	// End Line: 719

/* WARNING: Control flow encountered bad instruction data */
/* WARNING: Unknown calling convention yet parameter storage is locked */

int Menu_BootupInitGfx(void)

{
                    /* WARNING: Bad instruction - Truncating control flow here */
  halt_baddata();
}



// decompiled code
// original method signature: 
// int /*$ra*/ Menu_BootupDrawGfx()
 // line 373, offset 0x800bc234
	/* begin block 1 */
		// Start line: 777
	/* end block 1 */
	// End Line: 778

/* WARNING: Control flow encountered bad instruction data */
/* WARNING: Unknown calling convention yet parameter storage is locked */

int Menu_BootupDrawGfx(void)

{
                    /* WARNING: Bad instruction - Truncating control flow here */
  halt_baddata();
}



// decompiled code
// original method signature: 
// long /*$ra*/ Menu_BootupTestCard(int slot /*$s2*/)
 // line 382, offset 0x800bc340
	/* begin block 1 */
		// Start line: 383
		// Start offset: 0x800BC340
		// Variables:
	// 		long result; // $s0
	// 		char *text; // $a0
	/* end block 1 */
	// End offset: 0x800BC438
	// End Line: 426

	/* begin block 2 */
		// Start line: 801
	/* end block 2 */
	// End Line: 802

/* WARNING: Control flow encountered bad instruction data */

long Menu_BootupTestCard(int slot)

{
                    /* WARNING: Bad instruction - Truncating control flow here */
  halt_baddata();
}



// decompiled code
// original method signature: 
// long /*$ra*/ Menu_BootupWaitAnswer()
 // line 428, offset 0x800bc458
	/* begin block 1 */
		// Start line: 429
		// Start offset: 0x800BC458
		// Variables:
	// 		long result; // $s0
	/* end block 1 */
	// End offset: 0x800BC528
	// End Line: 456

	/* begin block 2 */
		// Start line: 914
	/* end block 2 */
	// End Line: 915

/* WARNING: Control flow encountered bad instruction data */
/* WARNING: Unknown calling convention yet parameter storage is locked */

long Menu_BootupWaitAnswer(void)

{
                    /* WARNING: Bad instruction - Truncating control flow here */
  halt_baddata();
}



// decompiled code
// original method signature: 
// long /*$ra*/ Menu_BootupCheck()
 // line 459, offset 0x800bc540
	/* begin block 1 */
		// Start line: 460
		// Start offset: 0x800BC540
		// Variables:
	// 		int test; // $v1
	/* end block 1 */
	// End offset: 0x800BC584
	// End Line: 473

	/* begin block 2 */
		// Start line: 985
	/* end block 2 */
	// End Line: 986

/* WARNING: Control flow encountered bad instruction data */
/* WARNING: Unknown calling convention yet parameter storage is locked */

long Menu_BootupCheck(void)

{
                    /* WARNING: Bad instruction - Truncating control flow here */
  halt_baddata();
}



// decompiled code
// original method signature: 
// long /*$ra*/ Menu_BootupRead()
 // line 474, offset 0x800bc594
	/* begin block 1 */
		// Start line: 475
		// Start offset: 0x800BC594
		// Variables:
	// 		int i; // $s0
	// 		char dummy[32]; // stack offset -56
	// 		long n; // stack offset -24
	// 		long free; // $a0
	/* end block 1 */
	// End offset: 0x800BC674
	// End Line: 503

	/* begin block 2 */
		// Start line: 1015
	/* end block 2 */
	// End Line: 1016

/* WARNING: Control flow encountered bad instruction data */
/* WARNING: Unknown calling convention yet parameter storage is locked */

long Menu_BootupRead(void)

{
                    /* WARNING: Bad instruction - Truncating control flow here */
  halt_baddata();
}



// decompiled code
// original method signature: 
// void /*$ra*/ Menu_TaskBootupMC()
 // line 506, offset 0x800bc688
	/* begin block 1 */
		// Start line: 507
		// Start offset: 0x800BC688
		// Variables:
	// 		long command; // stack offset -24
	// 		long result; // stack offset -20
	/* end block 1 */
	// End offset: 0x800BC75C
	// End Line: 546

	/* begin block 2 */
		// Start line: 1096
	/* end block 2 */
	// End Line: 1097

/* WARNING: Control flow encountered bad instruction data */
/* WARNING: Unknown calling convention yet parameter storage is locked */

void Menu_TaskBootupMC(void)

{
                    /* WARNING: Bad instruction - Truncating control flow here */
  halt_baddata();
}



// decompiled code
// original method signature: 
// void /*$ra*/ Menu_TaskBootup()
 // line 548, offset 0x800bc75c
	/* begin block 1 */
		// Start line: 549
		// Start offset: 0x800BC75C
		// Variables:
	// 		struct MENU_104fake TC; // stack offset -48

		/* begin block 1.1 */
			// Start line: 571
			// Start offset: 0x800BC820
		/* end block 1.1 */
		// End offset: 0x800BC854
		// End Line: 586
	/* end block 1 */
	// End offset: 0x800BC854
	// End Line: 587

	/* begin block 2 */
		// Start line: 1192
	/* end block 2 */
	// End Line: 1193

/* WARNING: Control flow encountered bad instruction data */
/* WARNING: Unknown calling convention yet parameter storage is locked */

void Menu_TaskBootup(void)

{
                    /* WARNING: Bad instruction - Truncating control flow here */
  halt_baddata();
}



// decompiled code
// original method signature: 
// long /*$ra*/ Menu_FirstBootup()
 // line 605, offset 0x800bc87c
	/* begin block 1 */
		// Start line: 1313
	/* end block 1 */
	// End Line: 1314

/* WARNING: Control flow encountered bad instruction data */
/* WARNING: Unknown calling convention yet parameter storage is locked */

long Menu_FirstBootup(void)

{
                    /* WARNING: Bad instruction - Truncating control flow here */
  halt_baddata();
}



// decompiled code
// original method signature: 
// void /*$ra*/ Menu_Launch(struct _PARAMETRE *main_p /*$s6*/)
 // line 622, offset 0x800bc9a0
	/* begin block 1 */
		// Start line: 623
		// Start offset: 0x800BC9A0
		// Variables:
	// 		int i; // $s2
	// 		int j; // $a0
	// 		struct MENU_70fake shp; // stack offset -48

		/* begin block 1.1 */
			// Start line: 774
			// Start offset: 0x800BCED8
			// Variables:
		// 		long i; // $s0
		/* end block 1.1 */
		// End offset: 0x800BCF34
		// End Line: 801
	/* end block 1 */
	// End offset: 0x800BCF8C
	// End Line: 826

	/* begin block 2 */
		// Start line: 1350
	/* end block 2 */
	// End Line: 1351

/* WARNING: Control flow encountered bad instruction data */

void Menu_Launch(_PARAMETRE *main_p)

{
                    /* WARNING: Bad instruction - Truncating control flow here */
  halt_baddata();
}



// decompiled code
// original method signature: 
// void /*$ra*/ Menu_InitGeneral()
 // line 849, offset 0x800bd044
	/* begin block 1 */
		// Start line: 850
		// Start offset: 0x800BD044
		// Variables:
	// 		int i; // $s6
	// 		int j; // $s5
	// 		struct MENU_70fake Shape; // stack offset -80
	/* end block 1 */
	// End offset: 0x800BDBD4
	// End Line: 1090

	/* begin block 2 */
		// Start line: 1874
	/* end block 2 */
	// End Line: 1875

/* WARNING: Control flow encountered bad instruction data */
/* WARNING: Unknown calling convention yet parameter storage is locked */

void Menu_InitGeneral(void)

{
                    /* WARNING: Bad instruction - Truncating control flow here */
  halt_baddata();
}



// decompiled code
// original method signature: 
// void /*$ra*/ Menu_TranslateSpecChar(void *script /*$a0*/)
 // line 1095, offset 0x800bdc04
	/* begin block 1 */
		// Start line: 1097
		// Start offset: 0x800BDC04
	/* end block 1 */
	// End offset: 0x800BDD98
	// End Line: 1179

	/* begin block 2 */
		// Start line: 2591
	/* end block 2 */
	// End Line: 2592

/* WARNING: Control flow encountered bad instruction data */

void Menu_TranslateSpecChar(void *script)

{
                    /* WARNING: Bad instruction - Truncating control flow here */
  halt_baddata();
}



// decompiled code
// original method signature: 
// void /*$ra*/ Menu_InitScripteString(void *scripte /*$a0*/)
 // line 1184, offset 0x800bdda0
	/* begin block 1 */
		// Start line: 2768
	/* end block 1 */
	// End Line: 2769

/* WARNING: Control flow encountered bad instruction data */

void Menu_InitScripteString(void *scripte)

{
                    /* WARNING: Bad instruction - Truncating control flow here */
  halt_baddata();
}



// decompiled code
// original method signature: 
// void /*$ra*/ Menu_InitScripteParam(void *scripte /*$a0*/)
 // line 1206, offset 0x800bde40
	/* begin block 1 */
		// Start line: 2811
	/* end block 1 */
	// End Line: 2812

/* WARNING: Control flow encountered bad instruction data */

void Menu_InitScripteParam(void *scripte)

{
                    /* WARNING: Bad instruction - Truncating control flow here */
  halt_baddata();
}



// decompiled code
// original method signature: 
// void /*$ra*/ Menu_NextLine()
 // line 1225, offset 0x800bdee0
	/* begin block 1 */
		// Start line: 2849
	/* end block 1 */
	// End Line: 2850

/* WARNING: Control flow encountered bad instruction data */
/* WARNING: Unknown calling convention yet parameter storage is locked */

void Menu_NextLine(void)

{
                    /* WARNING: Bad instruction - Truncating control flow here */
  halt_baddata();
}



// decompiled code
// original method signature: 
// char * /*$ra*/ Menu_NextTxt()
 // line 1238, offset 0x800bdf34
	/* begin block 1 */
		// Start line: 2875
	/* end block 1 */
	// End Line: 2876

/* WARNING: Control flow encountered bad instruction data */
/* WARNING: Unknown calling convention yet parameter storage is locked */

char * Menu_NextTxt(void)

{
                    /* WARNING: Bad instruction - Truncating control flow here */
  halt_baddata();
}



// decompiled code
// original method signature: 
// int /*$ra*/ Menu_NextParam()
 // line 1253, offset 0x800bdf88
	/* begin block 1 */
		// Start line: 2905
	/* end block 1 */
	// End Line: 2906

/* WARNING: Control flow encountered bad instruction data */
/* WARNING: Unknown calling convention yet parameter storage is locked */

int Menu_NextParam(void)

{
                    /* WARNING: Bad instruction - Truncating control flow here */
  halt_baddata();
}



// decompiled code
// original method signature: 
// void /*$ra*/ Menu_ReadPage()
 // line 1267, offset 0x800bdff0
	/* begin block 1 */
		// Start line: 1268
		// Start offset: 0x800BDFF0
		// Variables:
	// 		short Flag; // $s1
	// 		int i; // $s0
	// 		struct _OPTION *Opt; // $v1
	/* end block 1 */
	// End offset: 0x800BE3A4
	// End Line: 1378

	/* begin block 2 */
		// Start line: 2933
	/* end block 2 */
	// End Line: 2934

/* WARNING: Control flow encountered bad instruction data */
/* WARNING: Unknown calling convention yet parameter storage is locked */

void Menu_ReadPage(void)

{
                    /* WARNING: Bad instruction - Truncating control flow here */
  halt_baddata();
}



// decompiled code
// original method signature: 
// void /*$ra*/ Menu_InitPageGeneral()
 // line 1383, offset 0x800be3bc
	/* begin block 1 */
		// Start line: 1384
		// Start offset: 0x800BE3BC
		// Variables:
	// 		int i; // $s3
	/* end block 1 */
	// End offset: 0x800BE48C
	// End Line: 1401

	/* begin block 2 */
		// Start line: 3173
	/* end block 2 */
	// End Line: 3174

/* WARNING: Control flow encountered bad instruction data */
/* WARNING: Unknown calling convention yet parameter storage is locked */

void Menu_InitPageGeneral(void)

{
                    /* WARNING: Bad instruction - Truncating control flow here */
  halt_baddata();
}



// decompiled code
// original method signature: 
// void /*$ra*/ Menu_InitPageLoad()
 // line 1411, offset 0x800be4cc
	/* begin block 1 */
		// Start line: 1413
		// Start offset: 0x800BE4CC
		// Variables:
	// 		int i; // $a0
	/* end block 1 */
	// End offset: 0x800BE520
	// End Line: 1428

	/* begin block 2 */
		// Start line: 3276
	/* end block 2 */
	// End Line: 3277

/* WARNING: Control flow encountered bad instruction data */
/* WARNING: Unknown calling convention yet parameter storage is locked */

void Menu_InitPageLoad(void)

{
                    /* WARNING: Bad instruction - Truncating control flow here */
  halt_baddata();
}



// decompiled code
// original method signature: 
// void /*$ra*/ Menu_InitPageSelect()
 // line 1433, offset 0x800be528
	/* begin block 1 */
		// Start line: 1434
		// Start offset: 0x800BE528
		// Variables:
	// 		int i; // $s1
	/* end block 1 */
	// End offset: 0x800BE5D8
	// End Line: 1454

	/* begin block 2 */
		// Start line: 3317
	/* end block 2 */
	// End Line: 3318

/* WARNING: Control flow encountered bad instruction data */
/* WARNING: Unknown calling convention yet parameter storage is locked */

void Menu_InitPageSelect(void)

{
                    /* WARNING: Bad instruction - Truncating control flow here */
  halt_baddata();
}



// decompiled code
// original method signature: 
// void /*$ra*/ Menu_InitPageCenterScreen()
 // line 1467, offset 0x800be66c
	/* begin block 1 */
		// Start line: 1468
		// Start offset: 0x800BE66C
		// Variables:
	// 		int i; // $s2
	/* end block 1 */
	// End offset: 0x800BE6DC
	// End Line: 1478

	/* begin block 2 */
		// Start line: 3395
	/* end block 2 */
	// End Line: 3396

/* WARNING: Control flow encountered bad instruction data */
/* WARNING: Unknown calling convention yet parameter storage is locked */

void Menu_InitPageCenterScreen(void)

{
                    /* WARNING: Bad instruction - Truncating control flow here */
  halt_baddata();
}



// decompiled code
// original method signature: 
// void /*$ra*/ Menu_ReadCmd()
 // line 1483, offset 0x800be6f4
	/* begin block 1 */
		// Start line: 3451
	/* end block 1 */
	// End Line: 3452

/* WARNING: Control flow encountered bad instruction data */
/* WARNING: Unknown calling convention yet parameter storage is locked */

void Menu_ReadCmd(void)

{
                    /* WARNING: Bad instruction - Truncating control flow here */
  halt_baddata();
}



// decompiled code
// original method signature: 
// void /*$ra*/ Menu_CmdL()
 // line 1523, offset 0x800be7d4
	/* begin block 1 */
		// Start line: 1524
		// Start offset: 0x800BE7D4
		// Variables:
	// 		struct _OPTION *Opt; // $s0
	/* end block 1 */
	// End offset: 0x800BE7D4
	// End Line: 1524

	/* begin block 2 */
		// Start line: 3531
	/* end block 2 */
	// End Line: 3532

/* WARNING: Control flow encountered bad instruction data */
/* WARNING: Unknown calling convention yet parameter storage is locked */

void Menu_CmdL(void)

{
                    /* WARNING: Bad instruction - Truncating control flow here */
  halt_baddata();
}



// decompiled code
// original method signature: 
// void /*$ra*/ Menu_CmdS()
 // line 1544, offset 0x800be8ac
	/* begin block 1 */
		// Start line: 1545
		// Start offset: 0x800BE8AC
		// Variables:
	// 		struct _OPTION *Opt; // $s0
	/* end block 1 */
	// End offset: 0x800BE8AC
	// End Line: 1545

	/* begin block 2 */
		// Start line: 3585
	/* end block 2 */
	// End Line: 3586

/* WARNING: Control flow encountered bad instruction data */
/* WARNING: Unknown calling convention yet parameter storage is locked */

void Menu_CmdS(void)

{
                    /* WARNING: Bad instruction - Truncating control flow here */
  halt_baddata();
}



// decompiled code
// original method signature: 
// void /*$ra*/ Menu_CmdT()
 // line 1562, offset 0x800be958
	/* begin block 1 */
		// Start line: 3625
	/* end block 1 */
	// End Line: 3626

/* WARNING: Control flow encountered bad instruction data */
/* WARNING: Unknown calling convention yet parameter storage is locked */

void Menu_CmdT(void)

{
                    /* WARNING: Bad instruction - Truncating control flow here */
  halt_baddata();
}



// decompiled code
// original method signature: 
// void /*$ra*/ Menu_CmdB()
 // line 1570, offset 0x800be990
	/* begin block 1 */
		// Start line: 1571
		// Start offset: 0x800BE990
		// Variables:
	// 		short i; // $s3
	// 		short j; // $a1
	// 		struct _OPTION *Opt; // $s0
	// 		struct _DATA_B *DataB; // $s2
	/* end block 1 */
	// End offset: 0x800BEB80
	// End Line: 1629

	/* begin block 2 */
		// Start line: 3641
	/* end block 2 */
	// End Line: 3642

/* WARNING: Control flow encountered bad instruction data */
/* WARNING: Unknown calling convention yet parameter storage is locked */

void Menu_CmdB(void)

{
                    /* WARNING: Bad instruction - Truncating control flow here */
  halt_baddata();
}



// decompiled code
// original method signature: 
// void /*$ra*/ Menu_CmdM()
 // line 1632, offset 0x800beba4
	/* begin block 1 */
		// Start line: 1633
		// Start offset: 0x800BEBA4
		// Variables:
	// 		short n; // $s1
	// 		struct _OPTION *Opt; // $s3
	// 		struct _DATA_M *DataM; // $s2
	/* end block 1 */
	// End offset: 0x800BECB4
	// End Line: 1658

	/* begin block 2 */
		// Start line: 3847
	/* end block 2 */
	// End Line: 3848

/* WARNING: Control flow encountered bad instruction data */
/* WARNING: Unknown calling convention yet parameter storage is locked */

void Menu_CmdM(void)

{
                    /* WARNING: Bad instruction - Truncating control flow here */
  halt_baddata();
}



// decompiled code
// original method signature: 
// void /*$ra*/ Menu_PlayCd()
 // line 1669, offset 0x800bed04
	/* begin block 1 */
		// Start line: 1670
		// Start offset: 0x800BED04
	/* end block 1 */
	// End offset: 0x800BED04
	// End Line: 1670

	/* begin block 2 */
		// Start line: 3940
	/* end block 2 */
	// End Line: 3941

/* WARNING: Control flow encountered bad instruction data */
/* WARNING: Unknown calling convention yet parameter storage is locked */

void Menu_PlayCd(void)

{
                    /* WARNING: Bad instruction - Truncating control flow here */
  halt_baddata();
}



// decompiled code
// original method signature: 
// void /*$ra*/ Menu_PageLoadPSX()
 // line 1790, offset 0x800bed3c
	/* begin block 1 */
		// Start line: 1791
		// Start offset: 0x800BED3C
		// Variables:
	// 		int i; // $s0
	// 		int n; // $s1
	/* end block 1 */
	// End offset: 0x800BF230
	// End Line: 1945

	/* begin block 2 */
		// Start line: 4189
	/* end block 2 */
	// End Line: 4190

/* WARNING: Control flow encountered bad instruction data */
/* WARNING: Unknown calling convention yet parameter storage is locked */

void Menu_PageLoadPSX(void)

{
                    /* WARNING: Bad instruction - Truncating control flow here */
  halt_baddata();
}



// decompiled code
// original method signature: 
// void /*$ra*/ Menu_PageLoadPC()
 // line 1963, offset 0x800bf290
	/* begin block 1 */
		// Start line: 4615
	/* end block 1 */
	// End Line: 4616

/* WARNING: Control flow encountered bad instruction data */
/* WARNING: Unknown calling convention yet parameter storage is locked */

void Menu_PageLoadPC(void)

{
                    /* WARNING: Bad instruction - Truncating control flow here */
  halt_baddata();
}



// decompiled code
// original method signature: 
// void /*$ra*/ Menu_ChangeSector(int step /*$s0*/)
 // line 2021, offset 0x800bf298
	/* begin block 1 */
		// Start line: 4676
	/* end block 1 */
	// End Line: 4677

/* WARNING: Control flow encountered bad instruction data */

void Menu_ChangeSector(int step)

{
                    /* WARNING: Bad instruction - Truncating control flow here */
  halt_baddata();
}



// decompiled code
// original method signature: 
// void /*$ra*/ Menu_PageSelectPerso()
 // line 2034, offset 0x800bf398
	/* begin block 1 */
		// Start line: 2035
		// Start offset: 0x800BF398
		// Variables:
	// 		int i; // $s1
	// 		struct _SLIDE *Slide; // $a0
	/* end block 1 */
	// End offset: 0x800BF528
	// End Line: 2070

	/* begin block 2 */
		// Start line: 4703
	/* end block 2 */
	// End Line: 4704

/* WARNING: Control flow encountered bad instruction data */
/* WARNING: Unknown calling convention yet parameter storage is locked */

void Menu_PageSelectPerso(void)

{
                    /* WARNING: Bad instruction - Truncating control flow here */
  halt_baddata();
}



// decompiled code
// original method signature: 
// void /*$ra*/ Menu_LegalTask()
 // line 2074, offset 0x800bf564
	/* begin block 1 */
		// Start line: 4833
	/* end block 1 */
	// End Line: 4834

/* WARNING: Control flow encountered bad instruction data */
/* WARNING: Unknown calling convention yet parameter storage is locked */

void Menu_LegalTask(void)

{
                    /* WARNING: Bad instruction - Truncating control flow here */
  halt_baddata();
}



// decompiled code
// original method signature: 
// void /*$ra*/ Menu_Task()
 // line 2164, offset 0x800bf56c
	/* begin block 1 */
		// Start line: 2165
		// Start offset: 0x800BF56C
		// Variables:
	// 		int i; // $s1
	// 		int j; // $a0
	// 		struct MENU_104fake TC; // stack offset -72
	// 		short fx_handle; // $s6
	// 		struct _PERSO *Perso; // $t0
	// 		struct _PARAMETRE *p; // $t1
		// Labels:
		//		0x800BF5D8	Menu_Loop

		/* begin block 1.1 */
			// Start line: 2202
			// Start offset: 0x800BF628
		/* end block 1.1 */
		// End offset: 0x800BF638
		// End Line: 2222

		/* begin block 1.2 */
			// Start line: 2333
			// Start offset: 0x800BF9C0
			// Variables:
		// 		long maxl; // $s2
		/* end block 1.2 */
		// End offset: 0x800BFA78
		// End Line: 2360
	/* end block 1 */
	// End offset: 0x800BFD0C
	// End Line: 2476

	/* begin block 2 */
		// Start line: 4991
	/* end block 2 */
	// End Line: 4992

/* WARNING: Control flow encountered bad instruction data */
/* WARNING: Unknown calling convention yet parameter storage is locked */

void Menu_Task(void)

{
                    /* WARNING: Bad instruction - Truncating control flow here */
  halt_baddata();
}



// decompiled code
// original method signature: 
// void /*$ra*/ Menu_AddToStrList(char *s /*$a0*/, short a /*$a1*/, short y /*$a2*/, short f /*$a3*/, int n /*stack 16*/)
 // line 2521, offset 0x800bfeb4
	/* begin block 1 */
		// Start line: 5834
	/* end block 1 */
	// End Line: 5835

/* WARNING: Control flow encountered bad instruction data */

void Menu_AddToStrList(char *s,short a,short y,short f,int n)

{
                    /* WARNING: Bad instruction - Truncating control flow here */
  halt_baddata();
}



// decompiled code
// original method signature: 
// void /*$ra*/ Menu_MoveSelectGame(short p /*$a0*/)
 // line 2531, offset 0x800bff34
	/* begin block 1 */
		// Start line: 5858
	/* end block 1 */
	// End Line: 5859

/* WARNING: Control flow encountered bad instruction data */

void Menu_MoveSelectGame(short p)

{
                    /* WARNING: Bad instruction - Truncating control flow here */
  halt_baddata();
}



// decompiled code
// original method signature: 
// short /*$ra*/ Menu_BuildStrList(short slot /*$a0*/)
 // line 2549, offset 0x800c0004
	/* begin block 1 */
		// Start line: 2550
		// Start offset: 0x800C0004
		// Variables:
	// 		int i; // $s2
	// 		char dummy[20]; // stack offset -112
	// 		char szBuffer[50]; // stack offset -88
	// 		long n; // stack offset -32
	/* end block 1 */
	// End offset: 0x800C0138
	// End Line: 2587

	/* begin block 2 */
		// Start line: 5894
	/* end block 2 */
	// End Line: 5895

/* WARNING: Control flow encountered bad instruction data */

short Menu_BuildStrList(short slot)

{
                    /* WARNING: Bad instruction - Truncating control flow here */
  halt_baddata();
}



// decompiled code
// original method signature: 
// void /*$ra*/ Menu_TaskMemCard()
 // line 2591, offset 0x800c0158
	/* begin block 1 */
		// Start line: 2592
		// Start offset: 0x800C0158
		// Variables:
	// 		short slot; // $s1
	// 		long res; // $v1
	// 		int fileno; // $v1
	// 		int fcardstate; // $s2
	// 		long command; // stack offset -40
	// 		long result; // stack offset -36
	/* end block 1 */
	// End offset: 0x800C03CC
	// End Line: 2707

	/* begin block 2 */
		// Start line: 5998
	/* end block 2 */
	// End Line: 5999

/* WARNING: Control flow encountered bad instruction data */
/* WARNING: Unknown calling convention yet parameter storage is locked */

void Menu_TaskMemCard(void)

{
                    /* WARNING: Bad instruction - Truncating control flow here */
  halt_baddata();
}



// decompiled code
// original method signature: 
// void /*$ra*/ Menu_ToScreenStd(short Fr /*stack -48*/)
 // line 2841, offset 0x800c03cc
	/* begin block 1 */
		// Start line: 2842
		// Start offset: 0x800C03CC
		// Variables:
	// 		int i; // $s6
	// 		short r; // $a2
	// 		short g; // $a1
	// 		short b; // $a0
	// 		int bx1; // $t1
	// 		int bx2; // $t2
	// 		int by1; // $a3
	// 		int by2; // $t0
	// 		int bw; // $v0
	// 		char Fleche[2]; // stack offset -80
	// 		struct MENU_8fake col4; // stack offset -72
	// 		struct MENU_70fake BidonShp; // stack offset -64
	// 		struct _DATA_B *DataB; // $s0
	// 		struct _DATA_M *DataM; // $v1
	/* end block 1 */
	// End offset: 0x800C0A78
	// End Line: 2997

	/* begin block 2 */
		// Start line: 6551
	/* end block 2 */
	// End Line: 6552

/* WARNING: Control flow encountered bad instruction data */

void Menu_ToScreenStd(short Fr)

{
                    /* WARNING: Bad instruction - Truncating control flow here */
  halt_baddata();
}



// decompiled code
// original method signature: 
// void /*$ra*/ Menu_ToScreenTitle()
 // line 3001, offset 0x800c0aa8
	/* begin block 1 */
		// Start line: 3002
		// Start offset: 0x800C0AA8
	/* end block 1 */
	// End offset: 0x800C0AA8
	// End Line: 3002

	/* begin block 2 */
		// Start line: 7050
	/* end block 2 */
	// End Line: 7051

/* WARNING: Control flow encountered bad instruction data */
/* WARNING: Unknown calling convention yet parameter storage is locked */

void Menu_ToScreenTitle(void)

{
                    /* WARNING: Bad instruction - Truncating control flow here */
  halt_baddata();
}



// decompiled code
// original method signature: 
// void /*$ra*/ Menu_MireInit()
 // line 3023, offset 0x800c0b24
	/* begin block 1 */
		// Start line: 3024
		// Start offset: 0x800C0B24
		// Variables:
	// 		int i; // $s3
	// 		int n; // $s7
	/* end block 1 */
	// End offset: 0x800C0D74
	// End Line: 3065

	/* begin block 2 */
		// Start line: 7097
	/* end block 2 */
	// End Line: 7098

/* WARNING: Control flow encountered bad instruction data */
/* WARNING: Unknown calling convention yet parameter storage is locked */

void Menu_MireInit(void)

{
                    /* WARNING: Bad instruction - Truncating control flow here */
  halt_baddata();
}



// decompiled code
// original method signature: 
// void /*$ra*/ Menu_Mire()
 // line 3067, offset 0x800c0da4
	/* begin block 1 */
		// Start line: 7323
	/* end block 1 */
	// End Line: 7324

/* WARNING: Control flow encountered bad instruction data */
/* WARNING: Unknown calling convention yet parameter storage is locked */

void Menu_Mire(void)

{
                    /* WARNING: Bad instruction - Truncating control flow here */
  halt_baddata();
}



// decompiled code
// original method signature: 
// void /*$ra*/ Menu_ScreenSetup()
 // line 3089, offset 0x800c1014
	/* begin block 1 */
		// Start line: 3090
		// Start offset: 0x800C1014
		// Variables:
	// 		static int isinit; // offset 0x800c6c70
	/* end block 1 */
	// End offset: 0x800C1040
	// End Line: 3095

	/* begin block 2 */
		// Start line: 7409
	/* end block 2 */
	// End Line: 7410

/* WARNING: Control flow encountered bad instruction data */
/* WARNING: Unknown calling convention yet parameter storage is locked */

void Menu_ScreenSetup(void)

{
                    /* WARNING: Bad instruction - Truncating control flow here */
  halt_baddata();
}



// decompiled code
// original method signature: 
// void /*$ra*/ Menu_ToScreenHelp()
 // line 3114, offset 0x800c1100
	/* begin block 1 */
		// Start line: 3115
		// Start offset: 0x800C1100
		// Variables:
	// 		struct MENU_8fake col1; // stack offset -16
	/* end block 1 */
	// End offset: 0x800C13B0
	// End Line: 3263

	/* begin block 2 */
		// Start line: 7462
	/* end block 2 */
	// End Line: 7463

/* WARNING: Control flow encountered bad instruction data */
/* WARNING: Unknown calling convention yet parameter storage is locked */

void Menu_ToScreenHelp(void)

{
                    /* WARNING: Bad instruction - Truncating control flow here */
  halt_baddata();
}



// decompiled code
// original method signature: 
// void /*$ra*/ Menu_RestoreCenterScreen()
 // line 3264, offset 0x800c13c0
	/* begin block 1 */
		// Start line: 7766
	/* end block 1 */
	// End Line: 7767

/* WARNING: Control flow encountered bad instruction data */
/* WARNING: Unknown calling convention yet parameter storage is locked */

void Menu_RestoreCenterScreen(void)

{
                    /* WARNING: Bad instruction - Truncating control flow here */
  halt_baddata();
}



// decompiled code
// original method signature: 
// void /*$ra*/ Menu_UpdateCenterScreen()
 // line 3270, offset 0x800c1414
	/* begin block 1 */
		// Start line: 7784
	/* end block 1 */
	// End Line: 7785

/* WARNING: Control flow encountered bad instruction data */
/* WARNING: Unknown calling convention yet parameter storage is locked */

void Menu_UpdateCenterScreen(void)

{
                    /* WARNING: Bad instruction - Truncating control flow here */
  halt_baddata();
}



// decompiled code
// original method signature: 
// void /*$ra*/ Menu_ExitCenterScreen()
 // line 3276, offset 0x800c1468
	/* begin block 1 */
		// Start line: 7801
	/* end block 1 */
	// End Line: 7802

/* WARNING: Control flow encountered bad instruction data */
/* WARNING: Unknown calling convention yet parameter storage is locked */

void Menu_ExitCenterScreen(void)

{
                    /* WARNING: Bad instruction - Truncating control flow here */
  halt_baddata();
}



// decompiled code
// original method signature: 
// short /*$ra*/ Menu_ChkJoyCenterScreen(short fx_handle /*$s2*/)
 // line 3285, offset 0x800c14c4
	/* begin block 1 */
		// Start line: 3286
		// Start offset: 0x800C14C4
		// Variables:
	// 		long UpdateSound; // $s1
	/* end block 1 */
	// End offset: 0x800C1664
	// End Line: 3363

	/* begin block 2 */
		// Start line: 7822
	/* end block 2 */
	// End Line: 7823

/* WARNING: Control flow encountered bad instruction data */

short Menu_ChkJoyCenterScreen(short fx_handle)

{
                    /* WARNING: Bad instruction - Truncating control flow here */
  halt_baddata();
}



// decompiled code
// original method signature: 
// void /*$ra*/ Menu_InitChangePage(struct _OPTION *Opt /*$a0*/)
 // line 3365, offset 0x800c167c
	/* begin block 1 */
		// Start line: 3366
		// Start offset: 0x800C167C
		// Variables:
	// 		int i; // $s4
	/* end block 1 */
	// End offset: 0x800C17D4
	// End Line: 3396

	/* begin block 2 */
		// Start line: 7990
	/* end block 2 */
	// End Line: 7991

/* WARNING: Control flow encountered bad instruction data */

void Menu_InitChangePage(_OPTION *Opt)

{
                    /* WARNING: Bad instruction - Truncating control flow here */
  halt_baddata();
}



// decompiled code
// original method signature: 
// void /*$ra*/ Menu_ChkJoyCaseSPSX()
 // line 3448, offset 0x800c17f4
	/* begin block 1 */
		// Start line: 8165
	/* end block 1 */
	// End Line: 8166

/* WARNING: Control flow encountered bad instruction data */
/* WARNING: Unknown calling convention yet parameter storage is locked */

void Menu_ChkJoyCaseSPSX(void)

{
                    /* WARNING: Bad instruction - Truncating control flow here */
  halt_baddata();
}



// decompiled code
// original method signature: 
// short /*$ra*/ Menu_ChkJoy()
 // line 3523, offset 0x800c1a0c
	/* begin block 1 */
		// Start line: 3524
		// Start offset: 0x800C1A0C
		// Variables:
	// 		int i; // $s2
	// 		struct _OPTION *Opt; // $s1
	// 		struct _DATA_B *DataB; // $a1
	// 		struct _DATA_M *DataM; // $s0
	/* end block 1 */
	// End offset: 0x800C1E80
	// End Line: 3719

	/* begin block 2 */
		// Start line: 8318
	/* end block 2 */
	// End Line: 8319

/* WARNING: Control flow encountered bad instruction data */
/* WARNING: Unknown calling convention yet parameter storage is locked */

short Menu_ChkJoy(void)

{
                    /* WARNING: Bad instruction - Truncating control flow here */
  halt_baddata();
}



// decompiled code
// original method signature: 
// void /*$ra*/ Menu_MoveOpt(short p /*$a0*/)
 // line 3723, offset 0x800c1ea4
	/* begin block 1 */
		// Start line: 8745
	/* end block 1 */
	// End Line: 8746

/* WARNING: Control flow encountered bad instruction data */

void Menu_MoveOpt(short p)

{
                    /* WARNING: Bad instruction - Truncating control flow here */
  halt_baddata();
}



// decompiled code
// original method signature: 
// void /*$ra*/ Menu_SetParam(short p /*$a0*/, short c /*$a1*/)
 // line 3741, offset 0x800c1ff0
	/* begin block 1 */
		// Start line: 8784
	/* end block 1 */
	// End Line: 8785

/* WARNING: Control flow encountered bad instruction data */

void Menu_SetParam(short p,short c)

{
                    /* WARNING: Bad instruction - Truncating control flow here */
  halt_baddata();
}



// decompiled code
// original method signature: 
// short /*$ra*/ Menu_GetParam(short p /*$a0*/)
 // line 3778, offset 0x800c207c
	/* begin block 1 */
		// Start line: 8858
	/* end block 1 */
	// End Line: 8859

/* WARNING: Control flow encountered bad instruction data */

short Menu_GetParam(short p)

{
                    /* WARNING: Bad instruction - Truncating control flow here */
  halt_baddata();
}



// decompiled code
// original method signature: 
// void /*$ra*/ Menu_FctOpt(struct _OPTION *Opt /*$s6*/)
 // line 3815, offset 0x800c2128
	/* begin block 1 */
		// Start line: 3816
		// Start offset: 0x800C2128
		// Variables:
	// 		int i; // $s4
	// 		int tx; // $s2
	// 		int ty; // $s0
	// 		char string[3]; // stack offset -40
	/* end block 1 */
	// End offset: 0x800C262C
	// End Line: 4044

	/* begin block 2 */
		// Start line: 8931
	/* end block 2 */
	// End Line: 8932

/* WARNING: Control flow encountered bad instruction data */

void Menu_FctOpt(_OPTION *Opt)

{
                    /* WARNING: Bad instruction - Truncating control flow here */
  halt_baddata();
}



// decompiled code
// original method signature: 
// void /*$ra*/ Menu_TaskSfx()
 // line 4047, offset 0x800c2654
	/* begin block 1 */
		// Start line: 4048
		// Start offset: 0x800C2654
		// Variables:
	// 		short voice; // $s1
	/* end block 1 */
	// End offset: 0x800C2724
	// End Line: 4078

	/* begin block 2 */
		// Start line: 9481
	/* end block 2 */
	// End Line: 9482

/* WARNING: Control flow encountered bad instruction data */
/* WARNING: Unknown calling convention yet parameter storage is locked */

void Menu_TaskSfx(void)

{
                    /* WARNING: Bad instruction - Truncating control flow here */
  halt_baddata();
}



// decompiled code
// original method signature: 
// void /*$ra*/ Menu_TaskSnd3D()
 // line 4104, offset 0x800c2724
	/* begin block 1 */
		// Start line: 9657
	/* end block 1 */
	// End Line: 9658

/* WARNING: Control flow encountered bad instruction data */
/* WARNING: Unknown calling convention yet parameter storage is locked */

void Menu_TaskSnd3D(void)

{
                    /* WARNING: Bad instruction - Truncating control flow here */
  halt_baddata();
}



// decompiled code
// original method signature: 
// struct _OPTION * /*$ra*/ Menu_FindOpt(short d /*$a0*/)
 // line 4156, offset 0x800c272c
	/* begin block 1 */
		// Start line: 4158
		// Start offset: 0x800C272C
		// Variables:
	// 		short i; // $a1
	/* end block 1 */
	// End offset: 0x800C27A8
	// End Line: 4165

	/* begin block 2 */
		// Start line: 9720
	/* end block 2 */
	// End Line: 9721

/* WARNING: Control flow encountered bad instruction data */

_OPTION * Menu_FindOpt(short d)

{
                    /* WARNING: Bad instruction - Truncating control flow here */
  halt_baddata();
}



// decompiled code
// original method signature: 
// void /*$ra*/ Menu_FX()
 // line 4171, offset 0x800c27b0
	/* begin block 1 */
		// Start line: 4172
		// Start offset: 0x800C27B0
		// Variables:
	// 		int i; // $s0
	/* end block 1 */
	// End offset: 0x800C2800
	// End Line: 4181

	/* begin block 2 */
		// Start line: 9749
	/* end block 2 */
	// End Line: 9750

/* WARNING: Control flow encountered bad instruction data */
/* WARNING: Unknown calling convention yet parameter storage is locked */

void Menu_FX(void)

{
                    /* WARNING: Bad instruction - Truncating control flow here */
  halt_baddata();
}



// decompiled code
// original method signature: 
// short /*$ra*/ Fade_Execute(struct _FADE *Fade /*$s0*/)
 // line 4190, offset 0x800c2824
	/* begin block 1 */
		// Start line: 4191
		// Start offset: 0x800C2824
		// Variables:
	// 		struct MENU_8fake c1; // stack offset -32
	// 		struct MENU_8fake c2; // stack offset -24
	// 		short result; // $s1
	/* end block 1 */
	// End offset: 0x800C31DC
	// End Line: 4463

	/* begin block 2 */
		// Start line: 9794
	/* end block 2 */
	// End Line: 9795

/* WARNING: Control flow encountered bad instruction data */

short Fade_Execute(_FADE *Fade)

{
                    /* WARNING: Bad instruction - Truncating control flow here */
  halt_baddata();
}



// decompiled code
// original method signature: 
// void /*$ra*/ Fade_Init(struct _FADE *f /*$a0*/, struct MENU_8fake c1 /*stack 4*/, struct MENU_8fake c2 /*stack 8*/, short p /*$v0*/)
 // line 4468, offset 0x800c31f4
	/* begin block 1 */
		// Start line: 10552
	/* end block 1 */
	// End Line: 10553

/* WARNING: Control flow encountered bad instruction data */

void Fade_Init(_FADE *f,undefined1 c1,undefined1 c2,short p)

{
                    /* WARNING: Bad instruction - Truncating control flow here */
  halt_baddata();
}



// decompiled code
// original method signature: 
// short /*$ra*/ Fade_Calculate(struct _FADE *f /*$t1*/)
 // line 4481, offset 0x800c3258
	/* begin block 1 */
		// Start line: 10581
	/* end block 1 */
	// End Line: 10582

/* WARNING: Control flow encountered bad instruction data */

short Fade_Calculate(_FADE *f)

{
                    /* WARNING: Bad instruction - Truncating control flow here */
  halt_baddata();
}



// decompiled code
// original method signature: 
// void /*$ra*/ Fade_Set(struct _FADE *Fade /*$a0*/, short f /*$a1*/)
 // line 4500, offset 0x800c338c
	/* begin block 1 */
		// Start line: 10632
	/* end block 1 */
	// End Line: 10633

/* WARNING: Control flow encountered bad instruction data */

void Fade_Set(_FADE *Fade,short f)

{
                    /* WARNING: Bad instruction - Truncating control flow here */
  halt_baddata();
}



// decompiled code
// original method signature: 
// void /*$ra*/ Menu_TaskMotion()
 // line 4510, offset 0x800c339c
	/* begin block 1 */
		// Start line: 4511
		// Start offset: 0x800C339C
		// Variables:
	// 		long bBlink; // stack offset -64
	// 		int iCounter; // stack offset -60
	// 		struct MENU_7fake cpos; // stack offset -568
	// 		struct MENU_7fake opos; // stack offset -560
	// 		struct MENU_7fake a; // stack offset -552
	// 		struct MENU_7fake a_Objet; // stack offset -544
	// 		struct MENU_7fake an; // stack offset -536
	// 		struct MENU_6fake vect; // stack offset -528
	// 		struct MENU_6fake vect2; // stack offset -512
	// 		struct MENU_6fake to; // stack offset -496
	// 		struct MENU_5fake m_perso; // stack offset -480
	// 		struct MENU_5fake m_Objet; // stack offset -448
	// 		struct MENU_5fake m_Output; // stack offset -416
	// 		struct MENU_5fake light; // stack offset -384
	// 		struct MENU_5fake color_Objet; // stack offset -352
	// 		struct MENU_5fake m_temp; // stack offset -320
	// 		struct _ROTMATRIX color; // stack offset -288
	// 		struct _ROTMATRIX light_Objet; // stack offset -264
	// 		struct MENU_74fake (*tmd_Objet[14]); // stack offset -240
	// 		short OffsetY_Objet[14]; // stack offset -184
	// 		struct _OFFSET Geom[6]; // stack offset -152
	// 		void *Prs; // $s6
	// 		struct _PERSO *Perso; // $s3
	// 		int i; // $s1
	// 		int n; // $s0
	// 		int idperso; // $fp
	// 		struct MENU_104fake TC; // stack offset -128

		/* begin block 1.1 */
			// Start line: 4686
			// Start offset: 0x800C3B7C
			// Variables:
		// 		struct MENU_5fake mn64; // stack offset -96
		/* end block 1.1 */
		// End offset: 0x800C3EF4
		// End Line: 4746
	/* end block 1 */
	// End offset: 0x800C3F50
	// End Line: 4758

	/* begin block 2 */
		// Start line: 10651
	/* end block 2 */
	// End Line: 10652

/* WARNING: Control flow encountered bad instruction data */
/* WARNING: Unknown calling convention yet parameter storage is locked */

void Menu_TaskMotion(void)

{
                    /* WARNING: Bad instruction - Truncating control flow here */
  halt_baddata();
}



// decompiled code
// original method signature: 
// short /*$ra*/ Menu_GetMotionEvent(struct _PERSO *Perso /*$a0*/)
 // line 4767, offset 0x800c3f50
	/* begin block 1 */
		// Start line: 4769
		// Start offset: 0x800C3F50
		// Variables:
	// 		struct MENU_99fake *Anm; // $v1
	/* end block 1 */
	// End offset: 0x800C3F50
	// End Line: 4771

	/* begin block 2 */
		// Start line: 11292
	/* end block 2 */
	// End Line: 11293

/* WARNING: Control flow encountered bad instruction data */

short Menu_GetMotionEvent(_PERSO *Perso)

{
                    /* WARNING: Bad instruction - Truncating control flow here */
  halt_baddata();
}



// decompiled code
// original method signature: 
// void /*$ra*/ Menu_MotionSound(struct _PERSO *Perso /*$a0*/, long ID /*$s1*/)
 // line 4785, offset 0x800c3f78
	/* begin block 1 */
		// Start line: 4786
		// Start offset: 0x800C3F78
		// Variables:
	// 		short event; // $s0
	/* end block 1 */
	// End offset: 0x800C4068
	// End Line: 4804

	/* begin block 2 */
		// Start line: 11329
	/* end block 2 */
	// End Line: 11330

/* WARNING: Control flow encountered bad instruction data */

void Menu_MotionSound(_PERSO *Perso,long ID)

{
                    /* WARNING: Bad instruction - Truncating control flow here */
  halt_baddata();
}



// decompiled code
// original method signature: 
// void /*$ra*/ Menu_TaskCheat()
 // line 4834, offset 0x800c407c
	/* begin block 1 */
		// Start line: 4835
		// Start offset: 0x800C407C
		// Variables:
	// 		long i; // $s0
	// 		long c; // $s1
	// 		long n; // $s2
	// 		unsigned short t; // $s5
	/* end block 1 */
	// End offset: 0x800C423C
	// End Line: 4916

	/* begin block 2 */
		// Start line: 11432
	/* end block 2 */
	// End Line: 11433

/* WARNING: Control flow encountered bad instruction data */
/* WARNING: Unknown calling convention yet parameter storage is locked */

void Menu_TaskCheat(void)

{
                    /* WARNING: Bad instruction - Truncating control flow here */
  halt_baddata();
}



// decompiled code
// original method signature: 
// void /*$ra*/ Menu_ToScreenPermanent()
 // line 4921, offset 0x800c423c
	/* begin block 1 */
		// Start line: 4922
		// Start offset: 0x800C423C
		// Variables:
	// 		int i; // $s4
	/* end block 1 */
	// End offset: 0x800C473C
	// End Line: 4967

	/* begin block 2 */
		// Start line: 11725
	/* end block 2 */
	// End Line: 11726

/* WARNING: Control flow encountered bad instruction data */
/* WARNING: Unknown calling convention yet parameter storage is locked */

void Menu_ToScreenPermanent(void)

{
                    /* WARNING: Bad instruction - Truncating control flow here */
  halt_baddata();
}



// decompiled code
// original method signature: 
// void /*$ra*/ Menu_ToScreenSelect(char Id /*$s7*/, short Fr /*$a1*/)
 // line 4971, offset 0x800c476c
	/* begin block 1 */
		// Start line: 4972
		// Start offset: 0x800C476C
		// Variables:
	// 		int i; // $s2
	// 		int niveau; // $t1
	// 		int n; // $s3
	// 		int bx2; // $t1
	// 		int by2; // $t0
	// 		int bw; // $v1
	// 		struct _PERSO *Perso; // $s3
	// 		short Value[8]; // stack offset -64
	/* end block 1 */
	// End offset: 0x800C4E34
	// End Line: 5120

	/* begin block 2 */
		// Start line: 11956
	/* end block 2 */
	// End Line: 11957

/* WARNING: Control flow encountered bad instruction data */

void Menu_ToScreenSelect(char Id,short Fr)

{
                    /* WARNING: Bad instruction - Truncating control flow here */
  halt_baddata();
}



// decompiled code
// original method signature: 
// void /*$ra*/ Menu_InitSelect()
 // line 5124, offset 0x800c4e64
	/* begin block 1 */
		// Start line: 5125
		// Start offset: 0x800C4E64
		// Variables:
	// 		short i; // $s7
	// 		short j; // $s3
	// 		short k; // $fp
	// 		short Flag; // $s0
	// 		struct MENU_70fake Shape; // stack offset -64
	// 		struct _PERSO *Perso; // $s4
	/* end block 1 */
	// End offset: 0x800C54A0
	// End Line: 5247

	/* begin block 2 */
		// Start line: 12586
	/* end block 2 */
	// End Line: 12587

/* WARNING: Control flow encountered bad instruction data */
/* WARNING: Unknown calling convention yet parameter storage is locked */

void Menu_InitSelect(void)

{
                    /* WARNING: Bad instruction - Truncating control flow here */
  halt_baddata();
}



// decompiled code
// original method signature: 
// void /*$ra*/ Menu_ChkJoySelect()
 // line 5251, offset 0x800c54d0
	/* begin block 1 */
		// Start line: 5252
		// Start offset: 0x800C54D0
	/* end block 1 */
	// End offset: 0x800C5660
	// End Line: 5366

	/* begin block 2 */
		// Start line: 13010
	/* end block 2 */
	// End Line: 13011

/* WARNING: Control flow encountered bad instruction data */
/* WARNING: Unknown calling convention yet parameter storage is locked */

void Menu_ChkJoySelect(void)

{
                    /* WARNING: Bad instruction - Truncating control flow here */
  halt_baddata();
}



// decompiled code
// original method signature: 
// void /*$ra*/ Menu_ChangeSelect(short s /*$s1*/)
 // line 5370, offset 0x800c5670
	/* begin block 1 */
		// Start line: 5371
		// Start offset: 0x800C5670
		// Variables:
	// 		struct _SLIDE *Slide; // $a0
	/* end block 1 */
	// End offset: 0x800C5744
	// End Line: 5389

	/* begin block 2 */
		// Start line: 13253
	/* end block 2 */
	// End Line: 13254

/* WARNING: Control flow encountered bad instruction data */

void Menu_ChangeSelect(short s)

{
                    /* WARNING: Bad instruction - Truncating control flow here */
  halt_baddata();
}



// decompiled code
// original method signature: 
// void /*$ra*/ Menu_InitSlideX(struct _SLIDE *slide /*$a0*/, short xi /*$a1*/, short xt /*$a2*/, short time /*$a3*/)
 // line 5397, offset 0x800c5790
	/* begin block 1 */
		// Start line: 13316
	/* end block 1 */
	// End Line: 13317

/* WARNING: Control flow encountered bad instruction data */

void Menu_InitSlideX(_SLIDE *slide,short xi,short xt,short time)

{
                    /* WARNING: Bad instruction - Truncating control flow here */
  halt_baddata();
}



// decompiled code
// original method signature: 
// void /*$ra*/ Menu_InitSlideY(struct _SLIDE *slide /*$a0*/, short yi /*$a1*/, short yt /*$a2*/, short time /*$a3*/)
 // line 5410, offset 0x800c5834
	/* begin block 1 */
		// Start line: 13345
	/* end block 1 */
	// End Line: 13346

/* WARNING: Control flow encountered bad instruction data */

void Menu_InitSlideY(_SLIDE *slide,short yi,short yt,short time)

{
                    /* WARNING: Bad instruction - Truncating control flow here */
  halt_baddata();
}



// decompiled code
// original method signature: 
// short /*$ra*/ Menu_DoSlide(struct _SLIDE *slide /*$a1*/)
 // line 5424, offset 0x800c58d8
	/* begin block 1 */
		// Start line: 5425
		// Start offset: 0x800C58D8
		// Variables:
	// 		short flag; // $a2
	/* end block 1 */
	// End offset: 0x800C59A8
	// End Line: 5461

	/* begin block 2 */
		// Start line: 13373
	/* end block 2 */
	// End Line: 13374

/* WARNING: Control flow encountered bad instruction data */

short Menu_DoSlide(_SLIDE *slide)

{
                    /* WARNING: Bad instruction - Truncating control flow here */
  halt_baddata();
}



// decompiled code
// original method signature: 
// short /*$ra*/ Menu_SelectLevel()
 // line 5467, offset 0x800c59b0
	/* begin block 1 */
		// Start line: 5468
		// Start offset: 0x800C59B0
		// Variables:
	// 		struct MENU_8fake col; // stack offset -208
	// 		int i; // $s2
	// 		int maxl; // $s6
	// 		char txt[8]; // stack offset -200
	// 		char titre[8][20]; // stack offset -192
	/* end block 1 */
	// End offset: 0x800C5BC4
	// End Line: 5523

	/* begin block 2 */
		// Start line: 13461
	/* end block 2 */
	// End Line: 13462

/* WARNING: Control flow encountered bad instruction data */
/* WARNING: Unknown calling convention yet parameter storage is locked */

short Menu_SelectLevel(void)

{
                    /* WARNING: Bad instruction - Truncating control flow here */
  halt_baddata();
}



// decompiled code
// original method signature: 
// short /*$ra*/ Menu_SelectSector()
 // line 5528, offset 0x800c5bf0
	/* begin block 1 */
		// Start line: 5529
		// Start offset: 0x800C5BF0
		// Variables:
	// 		struct MENU_8fake col; // stack offset -48
	// 		int i; // $s1
	// 		char txt[10]; // stack offset -40
	/* end block 1 */
	// End offset: 0x800C5DA8
	// End Line: 5579

	/* begin block 2 */
		// Start line: 13643
	/* end block 2 */
	// End Line: 13644

/* WARNING: Control flow encountered bad instruction data */
/* WARNING: Unknown calling convention yet parameter storage is locked */

short Menu_SelectSector(void)

{
                    /* WARNING: Bad instruction - Truncating control flow here */
  halt_baddata();
}



// decompiled code
// original method signature: 
// void /*$ra*/ Menu_SwapBackground()
 // line 5582, offset 0x800c5dcc
	/* begin block 1 */
		// Start line: 5584
		// Start offset: 0x800C5DCC
		// Variables:
	// 		int i; // $t2
	// 		int j; // $a2
	// 		char buffer; // $a1
	/* end block 1 */
	// End offset: 0x800C5E44
	// End Line: 5614

	/* begin block 2 */
		// Start line: 13835
	/* end block 2 */
	// End Line: 13836

/* WARNING: Control flow encountered bad instruction data */
/* WARNING: Unknown calling convention yet parameter storage is locked */

void Menu_SwapBackground(void)

{
                    /* WARNING: Bad instruction - Truncating control flow here */
  halt_baddata();
}



// decompiled code
// original method signature: 
// void /*$ra*/ Menu_CreditsLaunch(short flag /*$a0*/)
 // line 5621, offset 0x800c5e4c
	/* begin block 1 */
		// Start line: 5622
		// Start offset: 0x800C5E4C
	/* end block 1 */
	// End offset: 0x800C5E4C
	// End Line: 5622

	/* begin block 2 */
		// Start line: 13902
	/* end block 2 */
	// End Line: 13903

/* WARNING: Control flow encountered bad instruction data */

void Menu_CreditsLaunch(short flag)

{
                    /* WARNING: Bad instruction - Truncating control flow here */
  halt_baddata();
}



// decompiled code
// original method signature: 
// void /*$ra*/ Menu_CreditsInitScript()
 // line 5683, offset 0x800c604c
	/* begin block 1 */
		// Start line: 5684
		// Start offset: 0x800C604C
		// Variables:
	// 		int i; // $s1
	/* end block 1 */
	// End offset: 0x800C61C8
	// End Line: 5741

	/* begin block 2 */
		// Start line: 14038
	/* end block 2 */
	// End Line: 14039

/* WARNING: Control flow encountered bad instruction data */
/* WARNING: Unknown calling convention yet parameter storage is locked */

void Menu_CreditsInitScript(void)

{
                    /* WARNING: Bad instruction - Truncating control flow here */
  halt_baddata();
}



// decompiled code
// original method signature: 
// void /*$ra*/ Menu_TaskCredits()
 // line 5743, offset 0x800c61e0
	/* begin block 1 */
		// Start line: 5744
		// Start offset: 0x800C61E0
		// Variables:
	// 		struct MENU_104fake TC; // stack offset -504
	// 		long i; // $s2
	// 		long y; // $s4
	// 		long n; // $s0
	// 		char String[256]; // stack offset -472
	// 		struct MENU_33fake face1[2]; // stack offset -216
	// 		struct MENU_33fake face2[2]; // stack offset -144
	// 		struct MENU_55fake Tpage1[2]; // stack offset -72
	// 		struct MENU_55fake Tpage2[2]; // stack offset -56
	/* end block 1 */
	// End offset: 0x800C6804
	// End Line: 5885

	/* begin block 2 */
		// Start line: 14167
	/* end block 2 */
	// End Line: 14168

/* WARNING: Control flow encountered bad instruction data */
/* WARNING: Unknown calling convention yet parameter storage is locked */

void Menu_TaskCredits(void)

{
                    /* WARNING: Bad instruction - Truncating control flow here */
  halt_baddata();
}



// autogenerated function stub: 
// void Menu_TabSector() /* Menu_TabSector method signature is not contained in the debug symbol data. This is likely either a library function or the game was compiled without debug symbols. Please refer to the TDR documentation for additional guidance. */
void Menu_TabSector() 
{ // line 8760, offset 0x800c68d4
	return null;
}




