#include "THISDUST.H"
#include "BOSS7.H"


// decompiled code
// original method signature: 
// void /*$ra*/ AhPuch_MinimizeDestructor(struct TASK *t /*$a0*/)
 // line 13, offset 0x800adc38
	/* begin block 1 */
		// Start line: 14
		// Start offset: 0x800ADC38
		// Variables:
	// 		struct _D3_OBJECT *o; // $v0
	// 		struct M_OBJECT *mo; // $s0
	/* end block 1 */
	// End offset: 0x800ADC38
	// End Line: 14

	/* begin block 2 */
		// Start line: 26
	/* end block 2 */
	// End Line: 27

/* WARNING: Control flow encountered bad instruction data */

void AhPuch_MinimizeDestructor(TASK *t)

{
                    /* WARNING: Bad instruction - Truncating control flow here */
  halt_baddata();
}



// decompiled code
// original method signature: 
// void /*$ra*/ AhPuch_Minimize()
 // line 23, offset 0x800adc70
	/* begin block 1 */
		// Start line: 24
		// Start offset: 0x800ADC70
		// Variables:
	// 		struct _D3_OBJECT *target; // $s2
	// 		struct M_OBJECT *mo; // $s1
	// 		long i; // $s0
	/* end block 1 */
	// End offset: 0x800ADDD0
	// End Line: 60

	/* begin block 2 */
		// Start line: 47
	/* end block 2 */
	// End Line: 48

/* WARNING: Control flow encountered bad instruction data */
/* WARNING: Unknown calling convention yet parameter storage is locked */

void AhPuch_Minimize(void)

{
                    /* WARNING: Bad instruction - Truncating control flow here */
  halt_baddata();
}



// decompiled code
// original method signature: 
// void /*$ra*/ Puch_Func_Reflex()
 // line 101, offset 0x800adde8
	/* begin block 1 */
		// Start line: 102
		// Start offset: 0x800ADDE8
		// Variables:
	// 		struct _MONSTER *monst; // $s0
	// 		struct _D3_OBJECT *o; // $s1
	// 		struct _D3_OBJECT *target; // $s2
	// 		long i; // $a0
	// 		long tmp; // $v1
	/* end block 1 */
	// End offset: 0x800AE03C
	// End Line: 178

	/* begin block 2 */
		// Start line: 209
	/* end block 2 */
	// End Line: 210

/* WARNING: Control flow encountered bad instruction data */
/* WARNING: Unknown calling convention yet parameter storage is locked */

void Puch_Func_Reflex(void)

{
                    /* WARNING: Bad instruction - Truncating control flow here */
  halt_baddata();
}



// decompiled code
// original method signature: 
// void /*$ra*/ Puch_Func_Decisions()
 // line 181, offset 0x800ae054
	/* begin block 1 */
		// Start line: 182
		// Start offset: 0x800AE054
		// Variables:
	// 		struct _MONSTER *monst; // $s0
	/* end block 1 */
	// End offset: 0x800AE0A0
	// End Line: 190

	/* begin block 2 */
		// Start line: 372
	/* end block 2 */
	// End Line: 373

/* WARNING: Control flow encountered bad instruction data */
/* WARNING: Unknown calling convention yet parameter storage is locked */

void Puch_Func_Decisions(void)

{
                    /* WARNING: Bad instruction - Truncating control flow here */
  halt_baddata();
}



// decompiled code
// original method signature: 
// void /*$ra*/ Puch_Task_Action()
 // line 193, offset 0x800ae0b0
	/* begin block 1 */
		// Start line: 194
		// Start offset: 0x800AE0B0
		// Variables:
	// 		struct BOSS7_8fake col; // stack offset -80
	// 		struct BOSS7_7fake pos; // stack offset -72
	// 		struct BOSS7_7fake posf; // stack offset -64
	// 		struct _MONSTER *monst; // $s6
	// 		struct _D3_OBJECT *o; // $s4
	// 		struct _D3_OBJECT *child; // $fp
	// 		struct _D3_OBJECT *father; // stack offset -56
	// 		struct _D3_OBJECT *target; // $s7
	// 		struct M_OBJECT *mo; // $s5
	// 		long i; // $s0
	// 		long x; // $s0
	// 		long y; // $t1
	// 		long tmp; // $v0
	/* end block 1 */
	// End offset: 0x800AF118
	// End Line: 585

	/* begin block 2 */
		// Start line: 405
	/* end block 2 */
	// End Line: 406

/* WARNING: Control flow encountered bad instruction data */
/* WARNING: Unknown calling convention yet parameter storage is locked */

void Puch_Task_Action(void)

{
                    /* WARNING: Bad instruction - Truncating control flow here */
  halt_baddata();
}





