#include "THISDUST.H"
#include "BOSS1.H"


// decompiled code
// original method signature: 
// void /*$ra*/ Golem_Hit()
 // line 34, offset 0x800adc1c
	/* begin block 1 */
		// Start line: 35
		// Start offset: 0x800ADC1C
		// Variables:
	// 		struct _MONSTER *monst; // $s0
	// 		struct _D3_OBJECT *o; // $s1
	// 		char old_resistance[10]; // stack offset -32
	// 		long i; // $a0
	/* end block 1 */
	// End offset: 0x800ADD18
	// End Line: 60

	/* begin block 2 */
		// Start line: 68
	/* end block 2 */
	// End Line: 69

/* WARNING: Control flow encountered bad instruction data */
/* WARNING: Unknown calling convention yet parameter storage is locked */

void Golem_Hit(void)

{
                    /* WARNING: Bad instruction - Truncating control flow here */
  halt_baddata();
}



// decompiled code
// original method signature: 
// void /*$ra*/ Golem_Func_Reflex()
 // line 101, offset 0x800add2c
	/* begin block 1 */
		// Start line: 102
		// Start offset: 0x800ADD2C
		// Variables:
	// 		struct _MONSTER *monst; // $s0
	// 		struct _D3_OBJECT *o; // $s1
	// 		struct _D3_OBJECT *target; // $s3
	// 		long tmp; // $v0
	// 		long i; // $s2
	// 		long x; // $s0
	/* end block 1 */
	// End offset: 0x800AE174
	// End Line: 197

	/* begin block 2 */
		// Start line: 224
	/* end block 2 */
	// End Line: 225

/* WARNING: Control flow encountered bad instruction data */
/* WARNING: Unknown calling convention yet parameter storage is locked */

void Golem_Func_Reflex(void)

{
                    /* WARNING: Bad instruction - Truncating control flow here */
  halt_baddata();
}



// decompiled code
// original method signature: 
// void /*$ra*/ Golem_Func_Decisions()
 // line 201, offset 0x800ae190
	/* begin block 1 */
		// Start line: 202
		// Start offset: 0x800AE190
		// Variables:
	// 		struct _MONSTER *monst; // $s0
	/* end block 1 */
	// End offset: 0x800AE1E0
	// End Line: 210

	/* begin block 2 */
		// Start line: 435
	/* end block 2 */
	// End Line: 436

/* WARNING: Control flow encountered bad instruction data */
/* WARNING: Unknown calling convention yet parameter storage is locked */

void Golem_Func_Decisions(void)

{
                    /* WARNING: Bad instruction - Truncating control flow here */
  halt_baddata();
}



// decompiled code
// original method signature: 
// void /*$ra*/ Golem_Task_Action()
 // line 213, offset 0x800ae1f0
	/* begin block 1 */
		// Start line: 214
		// Start offset: 0x800AE1F0
		// Variables:
	// 		struct BOSS1_7fake pos; // stack offset -40
	// 		struct _MONSTER *monst; // $s1
	// 		struct _D3_OBJECT *o; // $s2
	// 		struct M_OBJECT *mo; // $s4
	// 		long tmp; // $v0
	// 		long i; // $s0
	// 		long oldhp; // $s5
	/* end block 1 */
	// End offset: 0x800AE608
	// End Line: 326

	/* begin block 2 */
		// Start line: 461
	/* end block 2 */
	// End Line: 462

/* WARNING: Control flow encountered bad instruction data */
/* WARNING: Unknown calling convention yet parameter storage is locked */

void Golem_Task_Action(void)

{
                    /* WARNING: Bad instruction - Truncating control flow here */
  halt_baddata();
}



// decompiled code
// original method signature: 
// void /*$ra*/ Golem_Die()
 // line 340, offset 0x800ae644
	/* begin block 1 */
		// Start line: 341
		// Start offset: 0x800AE644
		// Variables:
	// 		struct BOSS1_7fake or_pos; // stack offset -40
	// 		struct BOSS1_7fake pos; // stack offset -32
	// 		struct _MONSTER *monst; // $v1
	// 		struct _D3_OBJECT *o; // $s2
	// 		struct M_OBJECT *mo; // $s0
	// 		struct M_OBJECT *mp; // $s0
	// 		struct _D3_OBJECT *Pieces; // $s1
	// 		long i; // $s3
	/* end block 1 */
	// End offset: 0x800AEA90
	// End Line: 424

	/* begin block 2 */
		// Start line: 786
	/* end block 2 */
	// End Line: 787

/* WARNING: Control flow encountered bad instruction data */
/* WARNING: Unknown calling convention yet parameter storage is locked */

void Golem_Die(void)

{
                    /* WARNING: Bad instruction - Truncating control flow here */
  halt_baddata();
}



// decompiled code
// original method signature: 
// void /*$ra*/ Golem_Shadow(struct _D3_OBJECT *obj /*$s1*/, struct BOSS1_31fake *pft4 /*$s2*/)
 // line 428, offset 0x800aeabc
	/* begin block 1 */
		// Start line: 429
		// Start offset: 0x800AEABC
		// Variables:
	// 		long zs; // $t1
	// 		long tmp; // $a0
	// 		struct BOSS1_7fake v[4]; // stack offset -48
	/* end block 1 */
	// End offset: 0x800AEE38
	// End Line: 456

	/* begin block 2 */
		// Start line: 1030
	/* end block 2 */
	// End Line: 1031

/* WARNING: Control flow encountered bad instruction data */

void Golem_Shadow(_D3_OBJECT *obj,undefined1 pft4)

{
                    /* WARNING: Bad instruction - Truncating control flow here */
  halt_baddata();
}



// decompiled code
// original method signature: 
// void /*$ra*/ Monster_Golem_Rock_Task()
 // line 459, offset 0x800aee50
	/* begin block 1 */
		// Start line: 460
		// Start offset: 0x800AEE50
		// Variables:
	// 		struct _D3_OBJECT *obj; // $s0
	// 		long speedx; // $s6
	// 		long speedy; // $s4
	// 		long speedz; // $s7
	// 		long posx; // $s3
	// 		long posy; // $s2
	// 		long posz; // $s1
	// 		long fallingrock; // $s4
	// 		long falldirection; // $s5
	// 		long divider; // $fp
	// 		struct BOSS1_70fake shp; // stack offset -136
	// 		struct BOSS1_31fake pft4[2]; // stack offset -120
	/* end block 1 */
	// End offset: 0x800AF090
	// End Line: 529

	/* begin block 2 */
		// Start line: 1099
	/* end block 2 */
	// End Line: 1100

/* WARNING: Control flow encountered bad instruction data */
/* WARNING: Unknown calling convention yet parameter storage is locked */

void Monster_Golem_Rock_Task(void)

{
                    /* WARNING: Bad instruction - Truncating control flow here */
  halt_baddata();
}



// decompiled code
// original method signature: 
// void /*$ra*/ Monster_Action_GolemDrop()
 // line 540, offset 0x800af0f4
	/* begin block 1 */
		// Start line: 541
		// Start offset: 0x800AF0F4
		// Variables:
	// 		struct _MONSTER *monst; // $v0
	// 		struct _D3_OBJECT *o; // $a1
	// 		struct _D3_OBJECT *rock; // $s0
	/* end block 1 */
	// End offset: 0x800AF150
	// End Line: 549

	/* begin block 2 */
		// Start line: 1337
	/* end block 2 */
	// End Line: 1338

/* WARNING: Control flow encountered bad instruction data */
/* WARNING: Unknown calling convention yet parameter storage is locked */

void Monster_Action_GolemDrop(void)

{
                    /* WARNING: Bad instruction - Truncating control flow here */
  halt_baddata();
}



// decompiled code
// original method signature: 
// void /*$ra*/ Golem_EffectTask()
 // line 552, offset 0x800af160
	/* begin block 1 */
		// Start line: 553
		// Start offset: 0x800AF160
		// Variables:
	// 		struct BOSS1_71fake list; // stack offset -48
	// 		struct BOSS1_7fake pos; // stack offset -32
	// 		struct _D3_OBJECT *o; // $s1
	/* end block 1 */
	// End offset: 0x800AF4C0
	// End Line: 595

	/* begin block 2 */
		// Start line: 1370
	/* end block 2 */
	// End Line: 1371

/* WARNING: Control flow encountered bad instruction data */
/* WARNING: Unknown calling convention yet parameter storage is locked */

void Golem_EffectTask(void)

{
                    /* WARNING: Bad instruction - Truncating control flow here */
  halt_baddata();
}



// decompiled code
// original method signature: 
// void /*$ra*/ Monster_Action_GolemThrow(short AnimNr /*$a0*/, short AnimEnd /*$s7*/, short mode /*$a2*/, struct _D3_OBJECT *target /*$s5*/)
 // line 599, offset 0x800af4e4
	/* begin block 1 */
		// Start line: 600
		// Start offset: 0x800AF4E4
		// Variables:
	// 		struct _MONSTER *monst; // $s6
	// 		struct _D3_OBJECT *o; // $s3
	// 		struct _D3_OBJECT *rock; // $s2
	// 		struct M_OBJECT *mo; // $s4
	// 		long distance; // $v1
	/* end block 1 */
	// End offset: 0x800AF750
	// End Line: 666

	/* begin block 2 */
		// Start line: 1512
	/* end block 2 */
	// End Line: 1513

/* WARNING: Control flow encountered bad instruction data */

void Monster_Action_GolemThrow(short AnimNr,short AnimEnd,short mode,_D3_OBJECT *target)

{
                    /* WARNING: Bad instruction - Truncating control flow here */
  halt_baddata();
}



// decompiled code
// original method signature: 
// void /*$ra*/ Golem_Bash_Ground(long AnimNr /*$a0*/, long mode /*$a1*/)
 // line 671, offset 0x800af79c
	/* begin block 1 */
		// Start line: 672
		// Start offset: 0x800AF79C
		// Variables:
	// 		struct BOSS1_7fake pos; // stack offset -32
	// 		struct _MONSTER *monst; // $s2
	// 		struct _D3_OBJECT *o; // $s0
	// 		struct M_OBJECT *mo; // $s1
	// 		struct _D3_OBJECT *target; // $s3
	/* end block 1 */
	// End offset: 0x800AF8FC
	// End Line: 701

	/* begin block 2 */
		// Start line: 1690
	/* end block 2 */
	// End Line: 1691

/* WARNING: Control flow encountered bad instruction data */

void Golem_Bash_Ground(long AnimNr,long mode)

{
                    /* WARNING: Bad instruction - Truncating control flow here */
  halt_baddata();
}



// decompiled code
// original method signature: 
// long /*$ra*/ Golem_Start_Sequence()
 // line 710, offset 0x800af948
	/* begin block 1 */
		// Start line: 711
		// Start offset: 0x800AF948
		// Variables:
	// 		struct _MONSTER *monst; // $s3
	// 		struct _D3_OBJECT *o; // $s2
	// 		struct M_OBJECT *mo; // $s5
	// 		struct _D3_OBJECT *target; // $s4
	// 		long i; // $s1
	// 		long xx; // $a0
	/* end block 1 */
	// End offset: 0x800AFADC
	// End Line: 742

	/* begin block 2 */
		// Start line: 1773
	/* end block 2 */
	// End Line: 1774

/* WARNING: Control flow encountered bad instruction data */
/* WARNING: Unknown calling convention yet parameter storage is locked */

long Golem_Start_Sequence(void)

{
                    /* WARNING: Bad instruction - Truncating control flow here */
  halt_baddata();
}



// autogenerated function stub: 
// void Golem_Explosion() /* Golem_Explosion method signature is not contained in the debug symbol data. This is likely either a library function or the game was compiled without debug symbols. Please refer to the TDR documentation for additional guidance. */
void Golem_Explosion() 
{ // line 1146, offset 0x800afbac
	return null;
}




