#include "THISDUST.H"
#include "BOSS4.H"


// decompiled code
// original method signature: 
// void /*$ra*/ Mutant_Func_Reflex()
 // line 50, offset 0x800adc34
	/* begin block 1 */
		// Start line: 51
		// Start offset: 0x800ADC34
		// Variables:
	// 		struct BOSS4_7fake pos; // stack offset -40
	// 		struct _MONSTER *monst; // $s1
	// 		struct _D3_OBJECT *o; // $s5
	// 		struct M_OBJECT *mo; // $a1
	// 		struct _D3_OBJECT *child; // $s3
	// 		struct M_OBJECT *mochild; // $a0
	// 		struct _D3_OBJECT *tmpobj; // $s0
	// 		long fathersOK; // $s4
	// 		long i; // $s2
	/* end block 1 */
	// End offset: 0x800AE084
	// End Line: 189

	/* begin block 2 */
		// Start line: 102
	/* end block 2 */
	// End Line: 103

/* WARNING: Control flow encountered bad instruction data */
/* WARNING: Unknown calling convention yet parameter storage is locked */

void Mutant_Func_Reflex(void)

{
                    /* WARNING: Bad instruction - Truncating control flow here */
  halt_baddata();
}



// decompiled code
// original method signature: 
// void /*$ra*/ Mutant_Func_Decisions()
 // line 192, offset 0x800ae0ac
	/* begin block 1 */
		// Start line: 193
		// Start offset: 0x800AE0AC
		// Variables:
	// 		struct _MONSTER *monst; // $s0
	/* end block 1 */
	// End offset: 0x800AE124
	// End Line: 209

	/* begin block 2 */
		// Start line: 405
	/* end block 2 */
	// End Line: 406

/* WARNING: Control flow encountered bad instruction data */
/* WARNING: Unknown calling convention yet parameter storage is locked */

void Mutant_Func_Decisions(void)

{
                    /* WARNING: Bad instruction - Truncating control flow here */
  halt_baddata();
}



// decompiled code
// original method signature: 
// void /*$ra*/ Mutant_AddParticle(struct _D3_OBJECT *o /*$a0*/, struct BOSS4_8fake *col /*$a1*/)
 // line 212, offset 0x800ae134
	/* begin block 1 */
		// Start line: 463
	/* end block 1 */
	// End Line: 464

/* WARNING: Control flow encountered bad instruction data */

void Mutant_AddParticle(_D3_OBJECT *o,undefined1 col)

{
                    /* WARNING: Bad instruction - Truncating control flow here */
  halt_baddata();
}



// decompiled code
// original method signature: 
// void /*$ra*/ Mutant_Smoke()
 // line 228, offset 0x800ae13c
	/* begin block 1 */
		// Start line: 229
		// Start offset: 0x800AE13C
		// Variables:
	// 		struct _D3_OBJECT *o; // $s1
	// 		struct BOSS4_7fake pos; // stack offset -32
	// 		long i; // $s0
	// 		long x; // $s3
	// 		long y; // $s2
	/* end block 1 */
	// End offset: 0x800AE22C
	// End Line: 259

	/* begin block 2 */
		// Start line: 483
	/* end block 2 */
	// End Line: 484

/* WARNING: Control flow encountered bad instruction data */
/* WARNING: Unknown calling convention yet parameter storage is locked */

void Mutant_Smoke(void)

{
                    /* WARNING: Bad instruction - Truncating control flow here */
  halt_baddata();
}



// decompiled code
// original method signature: 
// void /*$ra*/ Mutant_Task_Action()
 // line 263, offset 0x800ae248
	/* begin block 1 */
		// Start line: 264
		// Start offset: 0x800AE248
		// Variables:
	// 		struct BOSS4_8fake col; // stack offset -56
	// 		struct BOSS4_7fake pos; // stack offset -48
	// 		struct _MONSTER *monst; // $s4
	// 		struct _D3_OBJECT *o; // $s2
	// 		struct _D3_OBJECT *target; // $s6
	// 		struct _D3_OBJECT *child; // $s5
	// 		struct M_OBJECT *mo; // $s3
	// 		struct M_OBJECT *mochild; // $s7
	// 		long i; // $s0
	// 		long tmp; // $s1
	/* end block 1 */
	// End offset: 0x800AEA68
	// End Line: 455

	/* begin block 2 */
		// Start line: 576
	/* end block 2 */
	// End Line: 577

/* WARNING: Control flow encountered bad instruction data */
/* WARNING: Unknown calling convention yet parameter storage is locked */

void Mutant_Task_Action(void)

{
                    /* WARNING: Bad instruction - Truncating control flow here */
  halt_baddata();
}





