#include "THISDUST.H"
#include "BOSS6.H"


// decompiled code
// original method signature: 
// void /*$ra*/ Nessy_Func_Reflex()
 // line 50, offset 0x800adc5c
	/* begin block 1 */
		// Start line: 51
		// Start offset: 0x800ADC5C
		// Variables:
	// 		struct _MONSTER *monst; // $s0
	// 		struct _D3_OBJECT *o; // $s2
	// 		struct _D3_OBJECT *target; // $s4
	// 		struct M_OBJECT *mo; // $s3
	// 		struct _D3_OBJECT *child; // $s1
	// 		struct BOSS6_7fake pos; // stack offset -32
	/* end block 1 */
	// End offset: 0x800ADEA8
	// End Line: 104

	/* begin block 2 */
		// Start line: 101
	/* end block 2 */
	// End Line: 102

/* WARNING: Control flow encountered bad instruction data */
/* WARNING: Unknown calling convention yet parameter storage is locked */

void Nessy_Func_Reflex(void)

{
                    /* WARNING: Bad instruction - Truncating control flow here */
  halt_baddata();
}



// decompiled code
// original method signature: 
// long /*$ra*/ Nessy_GetSortedZones(struct _MONSTER *monst /*$a0*/, short *one /*$a1*/)
 // line 106, offset 0x800adec8
	/* begin block 1 */
		// Start line: 108
		// Start offset: 0x800ADEC8
		// Variables:
	// 		long i; // $v1
	// 		long tmp; // $t0
	// 		long tmp2; // $v1
	// 		unsigned long low; // $t1
	// 		unsigned long high; // $a0
	/* end block 1 */
	// End offset: 0x800ADFB4
	// End Line: 140

	/* begin block 2 */
		// Start line: 226
	/* end block 2 */
	// End Line: 227

/* WARNING: Control flow encountered bad instruction data */

long Nessy_GetSortedZones(_MONSTER *monst,short *one)

{
                    /* WARNING: Bad instruction - Truncating control flow here */
  halt_baddata();
}



// decompiled code
// original method signature: 
// void /*$ra*/ Nessy_Task_Action()
 // line 145, offset 0x800adfcc
	/* begin block 1 */
		// Start line: 146
		// Start offset: 0x800ADFCC
		// Variables:
	// 		struct BOSS6_8fake col; // stack offset -80
	// 		struct BOSS6_7fake pos; // stack offset -72
	// 		struct BOSS6_7fake rot; // stack offset -64
	// 		struct BOSS6_7fake pos2; // stack offset -56
	// 		struct _MONSTER *monst; // $s2
	// 		struct _D3_OBJECT *o; // $s3
	// 		struct M_OBJECT *mo; // $s1
	// 		struct _D3_OBJECT *target; // $s6
	// 		struct TASK *t; // $s0
	// 		struct _D3_OBJECT *circle; // $s5
	// 		struct _D3_OBJECT *tmpobj; // $v1
	// 		short zones[4]; // stack offset -48
	// 		long i; // $s0
	// 		long mirrory; // $s7
	/* end block 1 */
	// End offset: 0x800AEA68
	// End Line: 376

	/* begin block 2 */
		// Start line: 315
	/* end block 2 */
	// End Line: 316

/* WARNING: Control flow encountered bad instruction data */
/* WARNING: Unknown calling convention yet parameter storage is locked */

void Harb_Func_Decisions(void)

{
                    /* WARNING: Bad instruction - Truncating control flow here */
  halt_baddata();
}



// decompiled code
// original method signature: 
// void /*$ra*/ Dragon_GetHeadPosition(struct _MONSTER *monst /*$s5*/, struct M_OBJECT *mo /*$a1*/, struct BOSS6_7fake *pos /*$s6*/, long anim /*$a3*/)
 // line 408, offset 0x800aeab0
	/* begin block 1 */
		// Start line: 409
		// Start offset: 0x800AEAB0
		// Variables:
	// 		struct BOSS6_7fake *Traj; // $s2
	// 		long i; // $s1
	// 		long x; // $s3
	// 		long y; // $s1
	// 		long rot; // $s4
	/* end block 1 */
	// End offset: 0x800AEAB0
	// End Line: 409

	/* begin block 2 */
		// Start line: 997
	/* end block 2 */
	// End Line: 998

/* WARNING: Control flow encountered bad instruction data */

void Dragon_GetHeadPosition(_MONSTER *monst,M_OBJECT *mo,undefined1 pos,long anim)

{
                    /* WARNING: Bad instruction - Truncating control flow here */
  halt_baddata();
}



// decompiled code
// original method signature: 
// void /*$ra*/ Dragon_PlaySound(struct _D3_OBJECT *o /*$a0*/, long sound /*$a1*/)
 // line 428, offset 0x800aec88
	/* begin block 1 */
		// Start line: 429
		// Start offset: 0x800AEC88
		// Variables:
	// 		struct _D3_OBJECT *target; // $a1
	/* end block 1 */
	// End offset: 0x800AEC88
	// End Line: 429

	/* begin block 2 */
		// Start line: 1058
	/* end block 2 */
	// End Line: 1059

/* WARNING: Control flow encountered bad instruction data */

void Dragon_PlaySound(_D3_OBJECT *o,long sound)

{
                    /* WARNING: Bad instruction - Truncating control flow here */
  halt_baddata();
}



// decompiled code
// original method signature: 
// void /*$ra*/ Dragon_Func_Reflex()
 // line 436, offset 0x800aecc0
	/* begin block 1 */
		// Start line: 437
		// Start offset: 0x800AECC0
		// Variables:
	// 		struct BOSS6_7fake pos; // stack offset -40
	// 		struct _MONSTER *monst; // $s1
	// 		struct _D3_OBJECT *o; // $s3
	// 		struct _D3_OBJECT *target; // $s5
	// 		struct M_OBJECT *mo; // $s4
	// 		long x; // $s2
	// 		long y; // $v1
	/* end block 1 */
	// End offset: 0x800AF0A4
	// End Line: 527

	/* begin block 2 */
		// Start line: 1078
	/* end block 2 */
	// End Line: 1079

/* WARNING: Control flow encountered bad instruction data */
/* WARNING: Unknown calling convention yet parameter storage is locked */

void Dragon_Func_Reflex(void)

{
                    /* WARNING: Bad instruction - Truncating control flow here */
  halt_baddata();
}



// decompiled code
// original method signature: 
// void /*$ra*/ Dragon_Func_Decisions()
 // line 530, offset 0x800af0c8
	/* begin block 1 */
		// Start line: 532
		// Start offset: 0x800AF0C8
	/* end block 1 */
	// End offset: 0x800AF0C8
	// End Line: 533

	/* begin block 2 */
		// Start line: 1284
	/* end block 2 */
	// End Line: 1285

/* WARNING: Control flow encountered bad instruction data */
/* WARNING: Unknown calling convention yet parameter storage is locked */

void Dragon_Func_Decisions(void)

{
                    /* WARNING: Bad instruction - Truncating control flow here */
  halt_baddata();
}



// decompiled code
// original method signature: 
// void /*$ra*/ Dragon_Sound(struct _D3_OBJECT *o /*$s1*/, struct M_OBJECT *mo /*$s0*/)
 // line 535, offset 0x800af0d0
	/* begin block 1 */
		// Start line: 536
		// Start offset: 0x800AF0D0
		// Variables:
	// 		struct BOSS6_7fake pos; // stack offset -24
	/* end block 1 */
	// End offset: 0x800AF150
	// End Line: 549

	/* begin block 2 */
		// Start line: 1292
	/* end block 2 */
	// End Line: 1293

/* WARNING: Control flow encountered bad instruction data */

void Dragon_Sound(_D3_OBJECT *o,M_OBJECT *mo)

{
                    /* WARNING: Bad instruction - Truncating control flow here */
  halt_baddata();
}



// decompiled code
// original method signature: 
// void /*$ra*/ Dragon_Task_Action()
 // line 552, offset 0x800af164
	/* begin block 1 */
		// Start line: 553
		// Start offset: 0x800AF164
		// Variables:
	// 		struct BOSS6_8fake col; // stack offset -72
	// 		struct BOSS6_7fake pos; // stack offset -64
	// 		struct BOSS6_7fake rot; // stack offset -56
	// 		struct BOSS6_7fake pos2; // stack offset -48
	// 		struct _MONSTER *monst; // $s3
	// 		struct _D3_OBJECT *o; // $s2
	// 		struct M_OBJECT *mo; // $s1
	// 		struct _D3_OBJECT *target; // $s4
	// 		struct _ZONE *zone; // $s0
	// 		long i; // $s0
	// 		long fixx; // $fp
	// 		long fixy; // $s7
	/* end block 1 */
	// End offset: 0x800AFB70
	// End Line: 791

	/* begin block 2 */
		// Start line: 1331
	/* end block 2 */
	// End Line: 1332

/* WARNING: Control flow encountered bad instruction data */
/* WARNING: Unknown calling convention yet parameter storage is locked */

void Dragon_Task_Action(void)

{
                    /* WARNING: Bad instruction - Truncating control flow here */
  halt_baddata();
}



// autogenerated function stub: 
// void _boss2_sbss_obj() /* _boss2_sbss_obj method signature is not contained in the debug symbol data. This is likely either a library function or the game was compiled without debug symbols. Please refer to the TDR documentation for additional guidance. */
void _boss2_sbss_obj() 
{ // line 611, offset 0x800af40c
	return null;
}


// autogenerated function stub: 
// void _boss7_ctors_obj() /* _boss7_ctors_obj method signature is not contained in the debug symbol data. This is likely either a library function or the game was compiled without debug symbols. Please refer to the TDR documentation for additional guidance. */
void _boss7_ctors_obj() 
{ // line 803, offset 0x800af208
	return null;
}


// decompiled code
// original method signature: 
// void /*$ra*/ Nessy_Scripting(long dist /*$a0*/)
 // line 811, offset 0x800afbe0
	/* begin block 1 */
		// Start line: 812
		// Start offset: 0x800AFBE0
		// Variables:
	// 		struct _MONSTER *monst; // $s0
	// 		struct _D3_OBJECT *o; // $a0
	// 		struct _D3_OBJECT *target; // $v0
	/* end block 1 */
	// End offset: 0x800AFD10
	// End Line: 886

	/* begin block 2 */
		// Start line: 1942
	/* end block 2 */
	// End Line: 1943

/* WARNING: Control flow encountered bad instruction data */

void Nessy_Scripting(long dist)

{
                    /* WARNING: Bad instruction - Truncating control flow here */
  halt_baddata();
}



// autogenerated function stub: 
// void _boss1_ctors_obj() /* _boss1_ctors_obj method signature is not contained in the debug symbol data. This is likely either a library function or the game was compiled without debug symbols. Please refer to the TDR documentation for additional guidance. */
void _boss1_ctors_obj() 
{ // line 813, offset 0x800afc04
	return null;
}


// decompiled code
// original method signature: 
// void /*$ra*/ Dragon_Scripting(long dist /*$a0*/)
 // line 891, offset 0x800afd20
	/* begin block 1 */
		// Start line: 892
		// Start offset: 0x800AFD20
		// Variables:
	// 		struct _MONSTER *monst; // $s0
	// 		struct _D3_OBJECT *o; // $a1
	// 		struct _D3_OBJECT *target; // $v0
	/* end block 1 */
	// End offset: 0x800AFE2C
	// End Line: 932

	/* begin block 2 */
		// Start line: 2107
	/* end block 2 */
	// End Line: 2108

/* WARNING: Control flow encountered bad instruction data */

void Dragon_Scripting(long dist)

{
                    /* WARNING: Bad instruction - Truncating control flow here */
  halt_baddata();
}



// autogenerated function stub: 
// void GolemBeingHit() /* GolemBeingHit method signature is not contained in the debug symbol data. This is likely either a library function or the game was compiled without debug symbols. Please refer to the TDR documentation for additional guidance. */
void GolemBeingHit() 
{ // line 1136, offset 0x800afc00
	return null;
}


// autogenerated function stub: 
// void _boss6_sbss_obj() /* _boss6_sbss_obj method signature is not contained in the debug symbol data. This is likely either a library function or the game was compiled without debug symbols. Please refer to the TDR documentation for additional guidance. */
void _boss6_sbss_obj() 
{ // line 1260, offset 0x800afe3c
	return null;
}




